version: '3'
services:
  app: 
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27017
  admin-mongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234